fd = open("abc.txt","r+")
print "==>",fd.tell()
print fd.read(20)
print "current position",fd.tell()
fd.seek(0,0)
print "after seek(0,0) position",fd.tell()
print fd.read(30)
print "current position:",fd.tell()
fd.seek(0,1)
print "after seek(0,1) position:",fd.tell()
print fd.read(30)
print "after seek (0,1) position",fd.tell()
fd.seek(0,2)
print "after seek (0,2) position",fd.tell()
fd.write("alpha")
fd.close()

